<a href="https://colab.research.google.com/github/seva3/Silaev/blob/main/Numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hi')

hi


In [ ]:
# а. Импортируйте библиотеку NumPy
import numpy as np

In [ ]:
# b. Создайте массив из 10 нулей
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# c. Создать массив из 10 единиц
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# d. Создать массив из 10 пятерок
c = b*5
print(c)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
# e. Создать массив из целых чисел от 10 до 50
d = np.arange(10,51)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
# f. Создать массив из четных чисел от 10 до 50
f = np.arange(10,51,2)
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# g. Создать матрицу из 3*3 с числами от 0 до 8
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# h. Создать единичную матрицу 3*3
h = np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# i. Используйте NumPy для генерации случайного числа от 0 до 1
a = np.random.rand(1)
print(a)

[0.96669756]


In [ ]:
# j. Используйте NumPy для генерации массива из 25 случайных чисел
a = np.random.rand(25)
print(a)

[0.40968406 0.59852102 0.72226309 0.46451192 0.90553174 0.09754689
 0.92619059 0.03577996 0.90417397 0.646581   0.13332871 0.40853141
 0.70280397 0.80181542 0.81632535 0.38173876 0.28507289 0.65473699
 0.83531258 0.50965788 0.1823004  0.92556167 0.95364023 0.4738187
 0.26737839]


In [ ]:
# k. Создайте следующую матрицу, используя фун-ции библиотеки NumPy
a = np.arange(0, 1.01, 0.01)
print(a)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


In [ ]:
# l. Дана стартовая матрица (обязательно запустите код ниже в вашем решении!). Это матрица будет использоваться в последующих задачах
# стартовая матрица:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# l2. Написать код, который вернет следующую матрицу из стартовой
print('L=', mat[2:,1:])

L= [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
# m. Написать код обращения к элементу, который вернет значение 20 из стартовой матрицы задачи L
ar = mat[mat==20]
print(ar)

[20]


In [ ]:
# n. Написать код к стартовой матрице задачи L, который воспроизводит вывод, показанный ниже
print('a=', mat[0:3,1].reshape(3,1))

a= [[ 2]
 [ 7]
 [12]]


In [ ]:
# o. Написать код к стартовой матрице задачи L, который воспроизводит вывод, показанный ниже
print('a=', mat[4:])

a= [[21 22 23 24 25]]


In [ ]:
# p. Написать код к стартовой матрице задачи L, который воспроизводит вывод, показанный ниже
print('a=', mat[3:])

a= [[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# q. Получить сумму всех значений в стартовой матрице mat
print(mat.sum())

325


In [ ]:
# r. Получить стандартное отклонение в стартовой матрице mat 
print(mat.std())

7.211102550927978


In [ ]:
# s. Получить сумму значений в колонках в стартовой матрице mat
print(mat.sum(axis=0))

[55 60 65 70 75]
